name: "Build and Release Docker Image"
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build Docker Image
        run: nix build .#recorder.dockerImage
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load and push Docker image
        run: |
          version=$(nix eval --raw .#recorder.version)
          name=$(nix eval --raw .#recorder.pname)
          LOCAL_IMAGE="${name}:${version}"
          REMOTE_VERSIONED_IMAGE="ghcr.io/floriannadam/${name}:${version}"
          REMOTE_LATEST_IMAGE="ghcr.io/floriannadam/${name}:latest"
          docker load < result
          docker tag $LOCAL_IMAGE $REMOTE_VERSIONED_IMAGE
          docker push $REMOTE_VERSIONED_IMAGE
          docker tag $LOCAL_IMAGE $REMOTE_LATEST_IMAGE
          docker push $REMOTE_LATEST_IMAGE
